name: Run API tests

on: push

steps:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
     - uses: actions/checkout@v2

     - name: Setup jdk8
     - uses: actions/setup-java@v2
       with:
        java-version: '8'

     - name: Run tests
     - uses: mvn clean test -DxmlFile=api/apiTests.xml
     - continue-on-error: true

     - name: Generate Allure report
       uses: simple-elf/allure-report-action@master
       if: always()
       with:
         allure_results: target/allure-results
         allure_report: target/allure-report
         allure_history: target/allure-history
