name: Run API tests

on: push

permissions: write-all

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Setup jdk8
       uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'

     - name: Run tests
       run: mvn clean test -DxmlFile=api/apiTests.xml
       continue-on-error: true

#     - name: Generate Allure report
#       uses: simple-elf/allure-report-action@master
#       if: always()
#       with:
#         allure_results: target/allure-results
#         allure_report: target/allure-report
#         allure_history: target/allure-history

     - name: Generate Allure report
       uses: PavanMudigonda/allure-html-reporter-github-pages@v1.0
       if: always()
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         allure_results: target/allure-results
         gh_pages: gh-pages
